### PR TITLE
Sector API version update to 1.1.67

### PR DESCRIPTION
**Pull request by willeraab**
Updating the sector alarm API version to 1.1.67, and the asyncsector version to 0.1.6

### CODE REVIEW

**Review by sebastian-steinmann — APPROVED** [review]
ideally we would retrive the version from a request, but this solves the imidiate problem

**Comment by Pretagonist** [comment]
Isn't it kinda bad form to just try to guess a version string when the requests you are using might not work on newer versions?

Anyway the current version for the script is publicly visible in the html for the login page.

**Comment by sebastian-steinmann** [comment]
Could we get a merge & release of this @mgejke 
Since hassio moved all deps outside I cant see where I can just patch this directly

**Comment by mgejke** [comment]
It's merged, however, I'm away from home and can't update the packet on pypi...

**Pull request merged**
